before:
  hooks:
    - go mod download

builds:
  - id: kube-config-merger
    binary: kube-config-merger
    main: .

    env:
      - CGO_ENABLED=0

    goos:
      - linux
      - darwin
      - windows

    goarch:
      - amd64
      - arm
      - arm64
      - ppc64le
      - s390x

archives:
  - id: kube-config-merger-archive
    rlcp: true
    name_template: >-
      {{ .ProjectName }}_
      {{- title .Os }}_
      {{- if eq .Arch "amd64" }}x86_64
      {{- else if eq .Arch "386" }}i386
      {{- else }}{{ .Arch }}{{ end }}
    
    builds:
      - kube-config-merger
    
    format_overrides:
      - goos: windows
        format: zip
    
    files:
      - "LICENSE"

checksum:
  name_template: "checksums.txt"
  algorithm: sha256
